namespace SoulX {
  const audio=new Audio();audio.preload='metadata';let audioContext:AudioContext|undefined;let waveform:number[]=[];let activeBlobUrl='';let toastTimer=0;let dragId='';let editingSnapshotId='';let audioReadRevision=0;let importedCSV:string[]|undefined;let voiceFileData:{file:File;data:string;duration:number;peak:number;rms:number}|undefined;
  export function notify(message:string,error=false){ui.toast=message;ui.toastError=error;clearTimeout(toastTimer);const el=document.getElementById('toast');if(el){el.className='toast visible '+(error?'error':'');el.innerHTML=icon(error?'alert':'check',18)+'<span>'+escape(message)+'</span>';}toastTimer=window.setTimeout(()=>{ui.toast='';document.getElementById('toast')?.classList.remove('visible');},6500);}
  function openModal(name:string,data=''){ui.modal=name;ui.modalData=data;voiceFileData=undefined;audioReadRevision++;importedCSV=undefined;render();queueMicrotask(()=>{const modal=document.querySelector('.modal')!;const first=modal.querySelector<HTMLInputElement|HTMLTextAreaElement>('input:not([type="file"]),textarea,select')||modal.querySelector<HTMLButtonElement>('button');first?.focus();});}
  function closeModal(){audioReadRevision++;ui.modal='';ui.modalData=undefined;render();document.querySelector<HTMLElement>('.main-content button')?.focus({preventScroll:true});}
  function elementValue(id:string){return (document.getElementById(id) as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement)?.value||'';}
  function findTake(id:string){return allTakes().find(x=>x.take.id===id);}
  function selectProject(p:Project){state.activeProjectId=p.id;ui.selectedId=p.segments[0]?.id||'';ui.editorTab=p.mode==='dialogue'?'dialogue':'script';ui.page='editor';ui.search='';ui.modal='';persist().catch(e=>notify(e.message,true));render();}
  function makeProject(name:string,mode:'single'|'dialogue'='single',texts=['']){const p=newProject(name,mode,texts);state.projects.push(p);selectProject(p);notify('新项目已创建，原来的作品和草稿仍然保留。');}
  function removeSegment(id:string){const p=project(),s=p.segments.find(s=>s.id===id);if(!s||s.locked||s.takes.some(t=>['queued','running','paused'].includes(t.status)))throw new Error('锁定或存在活动任务的句子不能删除');remember();p.segments=p.segments.filter(s=>s.id!==id);ui.selectedId=p.segments[0]?.id||'';ui.modal='';changed();render();}
  async function action(name:string,el:HTMLElement){
    const id=el.dataset.id||'',p=project();
    switch(name){
      case 'nav':ui.page=el.dataset.page as Page;ui.mobileNav=false;ui.search='';ui.modal='';render();break;
      case 'mobile-nav':ui.mobileNav=!ui.mobileNav;render();break;
      case 'toggle-props':ui.propsOpen=!ui.propsOpen;render();break;
      case 'new-project':openModal('new-project');break;
      case 'new-dialogue':openModal('new-project','dialogue');break;
      case 'confirm-new-project':{const name=elementValue('new-project-name').trim();if(!name)throw new Error('请填写项目名称');makeProject(name,elementValue('new-project-mode')==='dialogue'?'dialogue':'single');break;}
      case 'rename-project':openModal('rename');break;
      case 'confirm-rename':{const value=elementValue('rename-input').trim();if(!value)throw new Error('名称不能为空');p.name=value.slice(0,120);changed();closeModal();break;}
      case 'open-project':{const selected=state.projects.find(x=>x.id===id);if(selected)selectProject(selected);break;}
      case 'archive-project':{const selected=state.projects.find(x=>x.id===id);if(selected){if(selected.segments.some(s=>s.takes.some(t=>['queued','running','paused'].includes(t.status))))throw new Error('项目仍有活动任务，请先完成或取消后归档');selected.archived=!selected.archived;await persist();render();notify(selected.archived?'项目已归档，未删除文稿和音频记录。':'项目已恢复。');}break;}
      case 'editor-tab':ui.editorTab=el.dataset.tab as AppUI['editorTab'];render();break;
      case 'select-sentence':ui.selectedId=id;render();break;
      case 'add-sentence':if(p.segments.length>=1000)throw new Error('每个项目最多 1000 句，请新建项目分批制作');remember();{const s=newSegment('',segment()?.voiceId||state.voices.find(v=>v.kind!=='placeholder'&&!v.deleted)!.id);p.segments.push(s);ui.selectedId=s.id;changed();render();document.getElementById('text-'+s.id)?.focus();}break;
      case 'toggle-lock':{const s=p.segments.find(x=>x.id===id);if(s){remember();s.locked=!s.locked;changed();render();notify(s.locked?'这句已锁定，批量修改和生成会跳过它。':'已解锁，可以继续修改。');}break;}
      case 'sentence-menu':openModal('sentence-menu',id);break;
      case 'copy-sentence':{const s=p.segments.find(x=>x.id===id);if(s){remember();const next={...clone(s),id:uid('seg'),takes:[],selectedTakeId:undefined,locked:false};p.segments.splice(p.segments.indexOf(s)+1,0,next);ui.selectedId=next.id;ui.modal='';changed();render();}break;}
      case 'move-up':case 'move-down':{const i=p.segments.findIndex(s=>s.id===id),j=i+(name==='move-up'?-1:1);if(i>=0&&j>=0&&j<p.segments.length){remember();[p.segments[i],p.segments[j]]=[p.segments[j],p.segments[i]];changed();}ui.modal='';render();break;}
      case 'split-sentence':{const s=p.segments.find(x=>x.id===id);if(!s||s.locked)break;if(s.takes.some(t=>['queued','running','paused'].includes(t.status)))throw new Error('该句有活动任务，不能拆分');const parts=splitText(s.text);if(parts.length<2)throw new Error('未找到可拆分的句末标点');if(s.takes.length)throw new Error('这句有历史版本，请先复制为新句再拆分，避免丢失引用');remember();const i=p.segments.indexOf(s);const next=parts.map(t=>newSegment(t,s.voiceId,s.role));p.segments.splice(i,1,...next);ui.selectedId=next[0].id;ui.modal='';changed();render();break;}
      case 'delete-sentence':{const s=p.segments.find(x=>x.id===id);if(s?.takes.length)openModal('confirm-delete-segment',id);else removeSegment(id);break;}
      case 'confirm-delete-segment':removeSegment(ui.modalData||'');break;
      case 'show-text-layers':openModal('text-layers',id);break;
      case 'save-subtitle-text':{const s=p.segments.find(x=>x.id===ui.modalData);if(s&&!s.locked){s.subtitleText=elementValue('subtitle-text');changed();}closeModal();break;}
      case 'undo':history('undo');break;case 'redo':history('redo');break;
      case 'open-import':openModal('import');break;
      case 'confirm-import':{const text=elementValue('import-text');const parts=(document.getElementById('split-by-sentence') as HTMLInputElement).checked?splitText(text):(importedCSV&&text===importedCSV.join('\n')?importedCSV:text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean));if(!parts.length)throw new Error('请先粘贴或选择文稿');if(p.segments.length+parts.length>1000)throw new Error('一个项目最多 1000 句，请拆成多个项目');if(parts.some(t=>t.length>50000))throw new Error('有文案过长，请先拆分');remember();const v=segment()?.voiceId||state.voices.find(v=>v.kind!=='placeholder'&&!v.deleted)?.id;if(!v)throw new Error('请先创建参考音色');const added=parts.map(t=>newSegment(t,v));if(p.segments.length===1&&!p.segments[0].text&&!p.segments[0].takes.length)p.segments=[];p.segments.push(...added);ui.selectedId=added[0].id;ui.page='editor';ui.modal='';changed();render();notify(`已追加 ${parts.length} 句，原有内容未被覆盖。`);break;}
      case 'open-batch':openModal('batch');break;
      case 'apply-batch-voice':remember();p.segments.filter(s=>!s.locked).forEach(s=>s.voiceId=elementValue('batch-voice'));changed();closeModal();notify('未锁定句子已统一音色。已有音频保留；不匹配的版本需重做。');break;
      case 'apply-batch-pause':{const value=Number(elementValue('batch-pause'));if(!Number.isFinite(value)||value<0||value>3)throw new Error('停顿范围为 0–3 秒');remember();p.segments.filter(s=>!s.locked).forEach(s=>s.pause=value);changed();closeModal();break;}
      case 'generate-selected':await generateSegments(segment()?[segment()!.id]:[]);break;
      case 'generate-all':await generateSegments(p.segments.map(s=>s.id));break;
      case 'generate-dirty':ui.modal='';await generateSegments(p.segments.filter(s=>!s.locked&&(!take(s)||take(s)?.status!=='completed'||!currentTakeMatches(s,take(s)))).map(s=>s.id));break;
      case 'select-take':{const s=p.segments.find(s=>s.id===el.dataset.segmentId);if(s){s.selectedTakeId=id;changed();render();}break;}
      case 'accept-take':{const found=findTake(id);if(!found)break;const t=found.take;if(t.test)throw new Error('测试音不能成为已验收的正式作品');if(t.status!=='completed'||!currentTakeMatches(found.segment,t))throw new Error('当前文稿或音色与音频版本不一致，不能验收');t.accepted=!t.accepted;await persist();render();notify(t.accepted?'此版本已标为人工验收通过；其他版本仍保留。':'已撤销此版本的验收标记。');break;}
      case 'play-take':{const s=p.segments.find(s=>s.id===el.dataset.segmentId);if(s&&take(s))await playTake(take(s)!);break;}
      case 'play-version':{const found=findTake(id);if(found)await playTake(found.take);break;}
      case 'preview-voice':{const v=voice(id);if(v)await previewVoice(v);break;}
      case 'playback-toggle':if(!audio.src)throw new Error('请先选择参考声音或已生成音频');if(audio.paused)await audio.play();else audio.pause();break;
      case 'restart-audio':audio.currentTime=0;updateAudioUI();break;
      case 'stop-audio':audio.pause();audio.currentTime=0;updateAudioUI();break;
      case 'favorite-voice':{const v=voice(id);if(v){v.favorite=!v.favorite;if(ui.connected&&v.serverIds[apiBase()])await api('/api/v1/voices/'+v.serverIds[apiBase()],{method:'PATCH',body:JSON.stringify({favorite:v.favorite})});await persist();render();}break;}
      case 'voice-filter':ui.voiceFilter=el.dataset.value||'全部';render();break;
      case 'project-filter':ui.projectFilter=el.dataset.value||'全部';render();break;
      case 'task-filter':ui.taskFilter=el.dataset.value||'全部';render();break;
      case 'use-voice':{const v=voice(id);if(!v||v.deleted||v.kind==='placeholder')throw new Error('此音色尚不可用');remember();p.segments.filter(s=>!s.locked).forEach(s=>s.voiceId=v.id);ui.page='editor';changed();render();notify('已应用到当前项目未锁定句子。');break;}
      case 'create-voice':openModal('create-voice',id);break;
      case 'confirm-create-voice':await saveVoice();break;
      case 'voice-detail':openModal('voice-detail',id);break;
      case 'delete-voice':{const v=voice(id);if(!v)break;const used=state.projects.some(p=>p.segments.some(s=>s.voiceId===id||s.takes.some(t=>t.voiceId===id)));if(used)throw new Error('有项目或历史版本引用此声音，不能直接删除。请保留声音资产。');v.deleted=true;await persist();closeModal();notify('音色已移入本地回收站。服务端原始文件未删除。');break;}
      case 'restore-voice':{const v=voice(id);if(v){v.deleted=false;await persist();closeModal();}break;}
      case 'use-template':{const t=templates.find(t=>t.id===id);if(t){const n=newProject(t.name,t.id==='dialogue'?'dialogue':'single',t.texts);n.category=t.tag;n.color=t.color;state.projects.push(n);selectProject(n);}break;}
      case 'connect':await connect();break;
      case 'enable-service-storage':await useServiceStorage();break;
      case 'confirm-service-storage':await useServiceStorage(true);break;
      case 'refresh-jobs':await pollJobs();render();break;
      case 'toggle-queue':{if(!ui.connected)throw new Error('尚未连接服务');await api('/api/v1/queue/'+(ui.health?.queue.paused?'resume':'pause'),{method:'POST'});ui.health=await api<Health>('/api/v3/studio/status');render();notify(ui.health.queue.paused?'队列已暂停领取新任务；不会强制中断正在生成的句子。':'队列已恢复。');break;}
      case 'cancel-job':case 'pause-job':case 'resume-job':{const found=findTake(id);if(found)await jobAction(found.take,name==='cancel-job'?'cancel':name==='pause-job'?'pause':'resume');break;}
      case 'retry-new':{const found=findTake(id);if(found){state.activeProjectId=found.project.id;ui.selectedId=found.segment.id;await generateSegments([found.segment.id]);}break;}
      case 'locate-take':{const found=findTake(id);if(found){state.activeProjectId=found.project.id;ui.selectedId=found.segment.id;found.segment.selectedTakeId=found.take.id;ui.page='editor';ui.editorTab='script';render();}break;}
      case 'recover-pending':for(const o of [...state.outbox])if(o.origin===apiBase())await sendPending(o);break;
      case 'open-export':openModal('export');break;
      case 'export-audio':{if(ui.busy)return;ui.busy=true;try{await exportAudio(el.dataset.format as 'zip'|'wav'|'mp3');}finally{ui.busy=false;}break;}
      case 'download-take':{const found=findTake(id);if(found){const t=found.take;if(t.origin!==apiBase()||!ui.connected)throw new Error('请先连接此音频所在服务');const blob=await requestBlob('/api/v1/tts/jobs/'+t.jobId+'/audio');downloadBlob(blob,`${t.test?'TEST_ONLY_':''}${t.jobId}.wav`);}break;}
      case 'export-workspace':exportJSON();break;
      case 'import-workspace':{const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{if(input.files?.[0])importWorkspace(input.files[0]).catch(e=>notify(e.message,true));};input.click();break;}
      case 'help':openModal('help');break;case 'close-modal':closeModal();break;
      default:throw new Error('未识别的操作：'+name);
    }
  }
  async function readAudio(file:File){if(file.size>20*1024*1024)throw new Error('参考文件不能超过 20 MB');if(!/\.(wav|mp3|m4a|aac|flac)$/i.test(file.name))throw new Error('请选择 WAV、MP3、M4A、AAC 或 FLAC');const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file);});const buffer=await file.arrayBuffer();audioContext??=new AudioContext();let decoded:AudioBuffer;try{decoded=await audioContext.decodeAudioData(buffer);}catch{throw new Error('浏览器无法解码这份音频，请转换为标准 WAV 后导入');}if(decoded.duration<0.4||decoded.duration>120)throw new Error('参考音频应为 0.4–120 秒，请先裁剪完整短句');const channel=decoded.getChannelData(0);let peak=0,sum=0;for(const x of channel){peak=Math.max(peak,Math.abs(x));sum+=x*x;}const rms=Math.sqrt(sum/channel.length);if(rms<0.0001)throw new Error('这段参考音频几乎无声，无法用于有效合成');let mime=data.replace(/^data:[^;]+;/,'data:'+(file.name.toLowerCase().endsWith('.mp3')?'audio/mpeg':file.name.toLowerCase().endsWith('.m4a')?'audio/mp4':file.name.toLowerCase().endsWith('.flac')?'audio/flac':file.name.toLowerCase().endsWith('.aac')?'audio/aac':'audio/wav')+';');return{file,data:mime,duration:decoded.duration,peak,rms};}
  async function saveVoice(){if(state.voices.length>=2000)throw new Error('声音数量已达 2000，请先备份并分工作区管理');const name=elementValue('voice-name').trim(),transcript=elementValue('voice-transcript').trim(),authorization=elementValue('voice-authorization').trim();if(!name||!transcript||!authorization)throw new Error('请填写音色名称、准确参考文字和授权依据');if(!(document.getElementById('voice-consent') as HTMLInputElement).checked)throw new Error('请先确认声音使用权与参考文字');if(!voiceFileData)throw new Error('请上传一段可正常解码的参考音频');const v:Voice={id:uid('voice'),name,transcript,authorization,region:elementValue('voice-region')||'粤语',dialect:'yue',style:elementValue('voice-style')||'自然',tags:elementValue('voice-tags').split(/[,，]/).map(s=>s.trim()).filter(Boolean),favorite:false,kind:'personal',color:'purple',audio:voiceFileData.data,serverIds:{}};state.voices.push(v);try{await persist();}catch(e){state.voices.pop();throw e;}ui.modal='';ui.page='voices';ui.voiceFilter='全部';render();notify('声音已保存到本地资产库。未上传服务，也未宣称训练了新模型。');}
  export function parseCSV(text:string):string[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;const src=text.replace(/^\uFEFF/,'');for(let i=0;i<src.length;i++){const c=src[i];if(c==='"'){if(quoted&&src[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&src[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw new Error('CSV 引号没有闭合，请检查文件');if(cell||row.length){row.push(cell);rows.push(row);}const index=rows[0]?.findIndex(h=>h.trim().toLowerCase()==='text');if(index===undefined||index<0)throw new Error('CSV 需要 text 列；音色可导入后在项目中统一设置');return rows.slice(1).map(r=>(r[index]||'').trim()).filter(Boolean);}
  export async function playTake(t:Take){if(!ui.connected||t.origin!==apiBase())throw new Error('请连接此版本音频所在的服务');if(t.status!=='completed')throw new Error('当前版本尚未生成完成');const blob=await requestBlob('/api/v1/tts/jobs/'+encodeURIComponent(t.jobId)+'/audio');await loadAudio(blob,`${t.test?'测试音 · ':''}${t.text.slice(0,38)}`,t.test?'仅链路测试 · 不是语音':'生成音频 · 请人工试听');}
  export async function previewVoice(v:Voice){if(v.kind==='placeholder')throw new Error('此卡片只是待创建的音色模板');let blob:Blob;if(v.audio)blob=await(await fetch(v.audio)).blob();else{if(!ui.connected||!v.serverIds[apiBase()])throw new Error('原参考声音只存在于服务端，请先连接对应服务');blob=await requestBlob('/api/v1/voices/'+v.serverIds[apiBase()]+'/audio');}await loadAudio(blob,v.name+' · 参考试听','参考音频 · 非当前文稿结果');}
  async function loadAudio(blob:Blob,label:string,kind:string){audio.pause();if(activeBlobUrl)URL.revokeObjectURL(activeBlobUrl);activeBlobUrl=URL.createObjectURL(blob);audio.src=activeBlobUrl;waveform=[];ui.playback={label,kind,url:activeBlobUrl,duration:0,current:0,playing:false};
    try{audioContext??=new AudioContext();const decoded=await audioContext.decodeAudioData(await blob.arrayBuffer());const values=decoded.getChannelData(0),step=Math.max(1,Math.floor(values.length/320));for(let i=0;i<320;i++){let peak=0;for(let j=i*step;j<Math.min((i+1)*step,values.length);j++)peak=Math.max(peak,Math.abs(values[j]));waveform.push(peak);}ui.playback.duration=decoded.duration;}catch{notify('可以尝试播放，但当前编码无法提取波形。',true);}
    if(ui.page!=='editor'){ui.page='editor';ui.modal='';}render();try{await audio.play();}catch{notify('浏览器未允许自动播放，请点击播放器中的播放按钮。',true);}updateAudioUI();}
  export function redrawAudio(){const canvas=document.getElementById('audio-waveform') as HTMLCanvasElement|null;if(!canvas)return;const rect=canvas.getBoundingClientRect();const ratio=devicePixelRatio||1;canvas.width=rect.width*ratio;canvas.height=68*ratio;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.scale(ratio,ratio);ctx.clearRect(0,0,rect.width,68);if(!waveform.length){ctx.strokeStyle='#e5eaf3';ctx.beginPath();ctx.moveTo(0,34);ctx.lineTo(rect.width,34);ctx.stroke();return;}const barWidth=rect.width/waveform.length;const maximum=Math.max(...waveform,0.1);waveform.forEach((value,i)=>{const h=Math.max(2,value/maximum*51);ctx.fillStyle=i/waveform.length<(ui.playback.duration?ui.playback.current/ui.playback.duration:0)?'#3375f6':'#bbcffa';ctx.fillRect(i*barWidth,34-h/2,Math.max(1,barWidth*.63),h);});}
  function updateAudioUI(){ui.playback.playing=!audio.paused;ui.playback.current=audio.currentTime||0;if(Number.isFinite(audio.duration))ui.playback.duration=audio.duration;const c=document.getElementById('audio-current'),d=document.getElementById('audio-duration'),seek=document.getElementById('audio-seek') as HTMLInputElement|null;if(c)c.textContent=fmtTime(ui.playback.current);if(d)d.textContent=fmtTime(ui.playback.duration);if(seek){seek.max=String(ui.playback.duration||1);seek.value=String(ui.playback.current);seek.disabled=!ui.playback.url;}const button=document.querySelector('[data-action="playback-toggle"]');if(button)button.innerHTML=icon(audio.paused?'play':'pause');redrawAudio();}
  audio.addEventListener('timeupdate',updateAudioUI);audio.addEventListener('loadedmetadata',updateAudioUI);audio.addEventListener('play',updateAudioUI);audio.addEventListener('pause',updateAudioUI);audio.addEventListener('ended',updateAudioUI);audio.addEventListener('error',()=>notify('音频播放失败，请检查源文件或重新下载。',true));
  document.addEventListener('click',e=>{const target=e.target as HTMLElement;const button=target.closest<HTMLElement>('[data-action]');if(button&&!(button as HTMLButtonElement).disabled){action(button.dataset.action!,button).catch(e=>{notify(e.message||String(e),true);});return;}if(target.matches('[data-modal-overlay]'))closeModal();});
  document.addEventListener('focusin',e=>{const target=e.target as HTMLElement;if(target.matches('[data-text-id]')){const id=target.dataset.textId!;if(ui.selectedId!==id){ui.selectedId=id;render();}if(editingSnapshotId!==id){remember();editingSnapshotId=id;}}});
  document.addEventListener('focusout',e=>{const target=e.target as HTMLElement;if(target.matches('[data-text-id]')){editingSnapshotId='';setTimeout(()=>{if(!document.activeElement?.closest('[data-action],input,select,textarea')&&!ui.modal)render();},100);}});
  document.addEventListener('input',e=>{const el=e.target as HTMLInputElement|HTMLTextAreaElement;if(el.dataset.textId){const s=project().segments.find(s=>s.id===el.dataset.textId);if(s&&!s.locked){s.text=el.value;changed();}return;}if(el.hasAttribute('data-search')){ui.search=el.value;render();return;}if(el.dataset.connection){(ui as any)[el.dataset.connection]=el.value;ui.connected=false;ui.health=undefined;return;}if(el.id==='audio-seek'){audio.currentTime=Number(el.value);updateAudioUI();return;}if(el.id==='pause-range'){const s=segment();if(s&&!s.locked){s.pause=Number(el.value);const label=document.getElementById('pause-value');if(label)label.textContent=s.pause.toFixed(2)+' 秒';changed();}return;}if(el.dataset.setting==='role'){const s=segment();if(s&&!s.locked){s.role=el.value;changed();}}});
  document.addEventListener('change',e=>{const el=e.target as HTMLInputElement|HTMLSelectElement;
    if(el.dataset.setting==='voiceId'){const s=segment();if(s&&!s.locked){remember();s.voiceId=el.value;changed();render();}}
    if(el.id==='playback-speed')audio.playbackRate=Number(el.value);
    if(el.id==='text-import-file'){const f=(el as HTMLInputElement).files?.[0];if(f){if(f.size>2*1024*1024){notify('文稿文件限 2 MB，请分章节处理。',true);return;}f.text().then(text=>{const isCSV=f.name.toLowerCase().endsWith('.csv');importedCSV=isCSV?parseCSV(text):undefined;const value=importedCSV?importedCSV.join('\n'):text;(document.getElementById('import-text') as HTMLTextAreaElement).value=value;if(isCSV)(document.getElementById('split-by-sentence') as HTMLInputElement).checked=false;notify('文件已读取，请检查文稿后确认追加。');}).catch(e=>notify(e.message,true));}}
    if(el.id==='voice-file'){const f=(el as HTMLInputElement).files?.[0];if(f){voiceFileData=undefined;const revision=++audioReadRevision;const status=document.getElementById('voice-file-check')!;status.textContent='正在读取并解码…';readAudio(f).then(d=>{if(revision!==audioReadRevision)return;voiceFileData=d;status.innerHTML=`${icon('check',16)}${escape(f.name)} · ${d.duration.toFixed(1)} 秒 · ${fmtSize(f.size)}${d.peak>=.995?' · 提示：峰值较高，请复核削波':''}`;}).catch(e=>{status.textContent=e.message;notify(e.message,true);});}}
  });
  document.addEventListener('dragstart',e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-drag-id]');if(target){dragId=target.dataset.dragId!;e.dataTransfer?.setData('text/plain',dragId);if(e.dataTransfer)e.dataTransfer.effectAllowed='move';}});
  document.addEventListener('dragover',e=>{if(dragId&&(e.target as HTMLElement).closest('[data-segment]'))e.preventDefault();});
  document.addEventListener('drop',e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-segment]');if(dragId&&target){e.preventDefault();const list=project().segments,from=list.findIndex(s=>s.id===dragId),to=list.findIndex(s=>s.id===target.dataset.segment);if(from>=0&&to>=0&&from!==to){remember();const [item]=list.splice(from,1);list.splice(to,0,item);changed();render();}dragId='';}});
  document.addEventListener('dragend',()=>dragId='');
  document.addEventListener('keydown',e=>{const editing=['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName);if(ui.modal){if(e.key==='Escape'){e.preventDefault();closeModal();return;}if(e.key==='Tab'){const focusable=[...document.querySelectorAll<HTMLElement>('.modal button:not([disabled]),.modal input:not([disabled]),.modal textarea,.modal select:not([disabled])')];const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}return;}
    if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();persist().then(()=>notify('工作区已保存。')).catch(e=>notify(e.message,true));}
    if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();generateSegments(segment()?[segment()!.id]:[]).catch(e=>notify(e.message,true));}
    if(!editing&&(e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?'redo':'undo');}
    if(!editing&&e.code==='Space'&&(e.target as HTMLElement).tagName!=='BUTTON'){e.preventDefault();if(audio.src){if(audio.paused)audio.play().catch(e=>notify(e.message,true));else audio.pause();}}
  });
  window.addEventListener('resize',redrawAudio);
  window.addEventListener('beforeunload',e=>{if(ui.saveStatus!=='saved'){e.preventDefault();e.returnValue='';}});
  async function boot(){await loadWorkspace();render();if(ui.baseUrl)await connect();setInterval(()=>pollJobs(),2400);}
  (window as any).SoulXApp={version:VERSION,getState:()=>clone(state),getUI:()=>({...ui,token:ui.token?'[redacted]':''}),validateWorkspace,parseCSV,splitText,save:()=>persist(),poll:()=>pollJobs(),render};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(e=>notify(e.message,true)));else boot().catch(e=>notify(e.message,true));
}
